2020-05-03 23:27:54,822:DEBUG:certbot._internal.main:certbot version: 1.3.0
2020-05-03 23:27:54,822:DEBUG:certbot._internal.main:Arguments: ['--agree-tos', '--no-eff-email', '-m', 'przemek.pokrywka@gmail.com', '--server', 'https://acme-staging-v02.api.letsencrypt.org/directory', '--manual', '--manual-public-ip-logging-ok', '--preferred-challenges', 'dns', '--manual-auth-hook', 'ls -lR /bot', '--manual-cleanup-hook', '/bot/certbotauthenticator', '-d', 'a.build.kyma-project.io.', '-v', '-n']
2020-05-03 23:27:54,822:DEBUG:certbot._internal.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#manual,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2020-05-03 23:27:55,140:DEBUG:certbot._internal.log:Root logging level set at 10
2020-05-03 23:27:55,143:INFO:certbot._internal.log:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2020-05-03 23:27:55,152:DEBUG:certbot._internal.plugins.selection:Requested authenticator manual and installer None
2020-05-03 23:27:55,161:DEBUG:certbot._internal.plugins.selection:Single candidate plugin: * manual
Description: Manual configuration or run your own shell scripts
Interfaces: IAuthenticator, IPlugin
Entry point: manual = certbot._internal.plugins.manual:Authenticator
Initialized: <certbot._internal.plugins.manual.Authenticator object at 0x7fac51bebac0>
Prep: True
2020-05-03 23:27:55,164:DEBUG:certbot._internal.plugins.selection:Selected authenticator <certbot._internal.plugins.manual.Authenticator object at 0x7fac51bebac0> and installer None
2020-05-03 23:27:55,165:INFO:certbot._internal.plugins.selection:Plugins selected: Authenticator manual, Installer None
2020-05-03 23:27:55,190:DEBUG:certbot._internal.main:Picked account: <Account(RegistrationResource(body=Registration(key=None, contact=(), agreement=None, status=None, terms_of_service_agreed=None, only_return_existing=None, external_account_binding=None), uri='https://acme-staging-v02.api.letsencrypt.org/acme/acct/13474575', new_authzr_uri=None, terms_of_service=None), 0ca10773bedaf0252bc041e7c5277c08, Meta(creation_dt=datetime.datetime(2020, 5, 3, 22, 46, 17, tzinfo=<UTC>), creation_host='1fe450f9cd72'))>
2020-05-03 23:27:55,193:DEBUG:acme.client:Sending GET request to https://acme-staging-v02.api.letsencrypt.org/directory.
2020-05-03 23:27:55,196:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): acme-staging-v02.api.letsencrypt.org:443
2020-05-03 23:27:55,954:DEBUG:urllib3.connectionpool:https://acme-staging-v02.api.letsencrypt.org:443 "GET /directory HTTP/1.1" 200 724
2020-05-03 23:27:55,957:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Sun, 03 May 2020 23:27:55 GMT
Content-Type: application/json
Content-Length: 724
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "keyChange": "https://acme-staging-v02.api.letsencrypt.org/acme/key-change",
  "meta": {
    "caaIdentities": [
      "letsencrypt.org"
    ],
    "termsOfService": "https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf",
    "website": "https://letsencrypt.org/docs/staging-environment/"
  },
  "newAccount": "https://acme-staging-v02.api.letsencrypt.org/acme/new-acct",
  "newNonce": "https://acme-staging-v02.api.letsencrypt.org/acme/new-nonce",
  "newOrder": "https://acme-staging-v02.api.letsencrypt.org/acme/new-order",
  "oF3JUX7GBVo": "https://community.letsencrypt.org/t/adding-random-entries-to-the-directory/33417",
  "revokeCert": "https://acme-staging-v02.api.letsencrypt.org/acme/revoke-cert"
}
2020-05-03 23:27:55,965:INFO:certbot._internal.main:Obtaining a new certificate
2020-05-03 23:27:56,019:DEBUG:certbot.crypto_util:Generating key (2048 bits): /etc/letsencrypt/keys/0008_key-certbot.pem
2020-05-03 23:27:56,029:DEBUG:certbot.crypto_util:Creating CSR: /etc/letsencrypt/csr/0008_csr-certbot.pem
2020-05-03 23:27:56,033:DEBUG:acme.client:Requesting fresh nonce
2020-05-03 23:27:56,034:DEBUG:acme.client:Sending HEAD request to https://acme-staging-v02.api.letsencrypt.org/acme/new-nonce.
2020-05-03 23:27:56,223:DEBUG:urllib3.connectionpool:https://acme-staging-v02.api.letsencrypt.org:443 "HEAD /acme/new-nonce HTTP/1.1" 200 0
2020-05-03 23:27:56,226:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Sun, 03 May 2020 23:27:56 GMT
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-staging-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: 0002Q0G_24KuDsYCHbbadISZ_JA6EXES5ijaOy297sDfnAM
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800


2020-05-03 23:27:56,229:DEBUG:acme.client:Storing nonce: 0002Q0G_24KuDsYCHbbadISZ_JA6EXES5ijaOy297sDfnAM
2020-05-03 23:27:56,231:DEBUG:acme.client:JWS payload:
b'{\n  "identifiers": [\n    {\n      "type": "dns",\n      "value": "a.build.kyma-project.io"\n    }\n  ]\n}'
2020-05-03 23:27:56,236:DEBUG:acme.client:Sending POST request to https://acme-staging-v02.api.letsencrypt.org/acme/new-order:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS1zdGFnaW5nLXYwMi5hcGkubGV0c2VuY3J5cHQub3JnL2FjbWUvYWNjdC8xMzQ3NDU3NSIsICJub25jZSI6ICIwMDAyUTBHXzI0S3VEc1lDSGJiYWRJU1pfSkE2RVhFUzVpamFPeTI5N3NEZm5BTSIsICJ1cmwiOiAiaHR0cHM6Ly9hY21lLXN0YWdpbmctdjAyLmFwaS5sZXRzZW5jcnlwdC5vcmcvYWNtZS9uZXctb3JkZXIifQ",
  "signature": "gFoYy4_KQCmkc0U8iKE7uDKnrLjVnzdyWukmT0gbnNcbDDXSCFBhWBgMwK1d9M6qDYDF749vQhci0qe6GY1pdiNgAZm4ioYaDtPN21Edrv_OOXyeNQz-3USrS4dYOWCfZfKijuKf2M_OWvIF32cyE0IipHpLkEZ1KHCxuy0RGaAw9p20peWg95hxq_TzV6WZ_BF82-fjdHLdelRRewxbBgoHXUQFFaClmN3J4892qTQHqf_bUecETTH926VzzgALHTdnbmuAw_OAlW1oph_ZiMxaozw6CmeEMg_hzAipTufB3VQW-AeQSQ0clMMbbskwBETi9mmi4U4E6bJrAZafug",
  "payload": "ewogICJpZGVudGlmaWVycyI6IFsKICAgIHsKICAgICAgInR5cGUiOiAiZG5zIiwKICAgICAgInZhbHVlIjogImEuYnVpbGQua3ltYS1wcm9qZWN0LmlvIgogICAgfQogIF0KfQ"
}
2020-05-03 23:27:56,456:DEBUG:urllib3.connectionpool:https://acme-staging-v02.api.letsencrypt.org:443 "POST /acme/new-order HTTP/1.1" 201 365
2020-05-03 23:27:56,459:DEBUG:acme.client:Received response:
HTTP 201
Server: nginx
Date: Sun, 03 May 2020 23:27:56 GMT
Content-Type: application/json
Content-Length: 365
Connection: keep-alive
Boulder-Requester: 13474575
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-staging-v02.api.letsencrypt.org/directory>;rel="index"
Location: https://acme-staging-v02.api.letsencrypt.org/acme/order/13474575/89387528
Replay-Nonce: 0001nFZeEpqlqpbx2Mwpioh1krQ5p3lhOM9bE38lbqnUzdc
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "status": "pending",
  "expires": "2020-05-10T23:27:56.335548145Z",
  "identifiers": [
    {
      "type": "dns",
      "value": "a.build.kyma-project.io"
    }
  ],
  "authorizations": [
    "https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/53681427"
  ],
  "finalize": "https://acme-staging-v02.api.letsencrypt.org/acme/finalize/13474575/89387528"
}
2020-05-03 23:27:56,463:DEBUG:acme.client:Storing nonce: 0001nFZeEpqlqpbx2Mwpioh1krQ5p3lhOM9bE38lbqnUzdc
2020-05-03 23:27:56,466:DEBUG:acme.client:JWS payload:
b''
2020-05-03 23:27:56,470:DEBUG:acme.client:Sending POST request to https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/53681427:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS1zdGFnaW5nLXYwMi5hcGkubGV0c2VuY3J5cHQub3JnL2FjbWUvYWNjdC8xMzQ3NDU3NSIsICJub25jZSI6ICIwMDAxbkZaZUVwcWxxcGJ4Mk13cGlvaDFrclE1cDNsaE9NOWJFMzhsYnFuVXpkYyIsICJ1cmwiOiAiaHR0cHM6Ly9hY21lLXN0YWdpbmctdjAyLmFwaS5sZXRzZW5jcnlwdC5vcmcvYWNtZS9hdXRoei12My81MzY4MTQyNyJ9",
  "signature": "mI_aMIp9hWrKatlhVSKpbtjYHyTp8GD5zIrm4-FU-NijNuoQE18aFbznvczzdfMDuEwz91Auv92VdbfumNKJt0gKgsWSoIMbvtbi06n0ODApYIcgZRShzvZb0yl455x8iKlgbz_uOExgiNre8sfwoIMRw6C4paRViGONs2U9cCt__JBVays0pn9rxnVv8-nfCeBQZqzaQ7ckiA0FGM_YJf85iZzeVMPcEfBl6GDzOBJNfzDoFBY1_URuWOc8UwgY_7k4ySC-SD1dYypWA30444YhOlN0ZJHfCqMSAPzz2CF6FnScViOuLsGoifSa-dmE5Lhmx4oAZHUe8xoncxvdZw",
  "payload": ""
}
2020-05-03 23:27:56,661:DEBUG:urllib3.connectionpool:https://acme-staging-v02.api.letsencrypt.org:443 "POST /acme/authz-v3/53681427 HTTP/1.1" 200 819
2020-05-03 23:27:56,664:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Sun, 03 May 2020 23:27:56 GMT
Content-Type: application/json
Content-Length: 819
Connection: keep-alive
Boulder-Requester: 13474575
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-staging-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: 0002WByc38a_zwJX9izE27hxs1fHlbGtLE0kkIIWkVDQHws
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "identifier": {
    "type": "dns",
    "value": "a.build.kyma-project.io"
  },
  "status": "pending",
  "expires": "2020-05-10T23:27:56Z",
  "challenges": [
    {
      "type": "http-01",
      "status": "pending",
      "url": "https://acme-staging-v02.api.letsencrypt.org/acme/chall-v3/53681427/iRF_Tw",
      "token": "IMpnBBejNopbCycmUcmsLdusQSz0ZW1g4eD-hgesL7c"
    },
    {
      "type": "dns-01",
      "status": "pending",
      "url": "https://acme-staging-v02.api.letsencrypt.org/acme/chall-v3/53681427/fhQ4qg",
      "token": "IMpnBBejNopbCycmUcmsLdusQSz0ZW1g4eD-hgesL7c"
    },
    {
      "type": "tls-alpn-01",
      "status": "pending",
      "url": "https://acme-staging-v02.api.letsencrypt.org/acme/chall-v3/53681427/OG0JcQ",
      "token": "IMpnBBejNopbCycmUcmsLdusQSz0ZW1g4eD-hgesL7c"
    }
  ]
}
2020-05-03 23:27:56,666:DEBUG:acme.client:Storing nonce: 0002WByc38a_zwJX9izE27hxs1fHlbGtLE0kkIIWkVDQHws
2020-05-03 23:27:56,668:INFO:certbot._internal.auth_handler:Performing the following challenges:
2020-05-03 23:27:56,670:INFO:certbot._internal.auth_handler:dns-01 challenge for a.build.kyma-project.io
2020-05-03 23:27:56,673:INFO:certbot._internal.hooks:Running manual-auth-hook command: ls -lR /bot
2020-05-03 23:27:56,706:INFO:certbot._internal.hooks:Output from manual-auth-hook command ls:
/bot:
total 14804
-rwxr-xr-x    1 root     root            60 May  3 23:24 certbotauthenticator
-rwxr-xr-x    1 root     root      15077836 May  3 23:22 certbotauthenticator_backup
drwxr-xr-x   19 root     root           608 May  3 23:27 log
-rw-r--r--    1 root     root          1359 May  3 23:22 main.go

/bot/log:
total 216
-rw-r--r--    1 root     root          9743 May  3 23:27 letsencrypt.log
-rw-r--r--    1 root     root         50905 May  3 23:26 letsencrypt.log.1
-rw-r--r--    1 root     root         16208 May  3 22:47 letsencrypt.log.10
-rw-r--r--    1 root     root         18190 May  3 22:46 letsencrypt.log.11
-rw-r--r--    1 root     root          2908 May  3 22:42 letsencrypt.log.12
-rw-r--r--    1 root     root          3309 May  3 22:38 letsencrypt.log.13
-rw-r--r--    1 root     root          2902 May  3 22:36 letsencrypt.log.14
-rw-r--r--    1 root     root             0 May  3 22:36 letsencrypt.log.15
-rw-r--r--    1 root     root         17868 May  3 23:24 letsencrypt.log.2
-rw-r--r--    1 root     root         16209 May  3 23:22 letsencrypt.log.3
-rw-r--r--    1 root     root         16209 May  3 23:20 letsencrypt.log.4
-rw-r--r--    1 root     root          3212 May  3 23:19 letsencrypt.log.5
-rw-r--r--    1 root     root         16209 May  3 23:15 letsencrypt.log.6
-rw-r--r--    1 root     root         16209 May  3 23:10 letsencrypt.log.7
-rw-r--r--    1 root     root          4851 May  3 23:01 letsencrypt.log.8
-rw-r--r--    1 root     root          4851 May  3 23:00 letsencrypt.log.9

2020-05-03 23:27:56,710:INFO:certbot._internal.auth_handler:Waiting for verification...
2020-05-03 23:27:56,711:DEBUG:acme.client:JWS payload:
b'{\n  "resource": "challenge",\n  "type": "dns-01"\n}'
2020-05-03 23:27:56,713:DEBUG:acme.client:Sending POST request to https://acme-staging-v02.api.letsencrypt.org/acme/chall-v3/53681427/fhQ4qg:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS1zdGFnaW5nLXYwMi5hcGkubGV0c2VuY3J5cHQub3JnL2FjbWUvYWNjdC8xMzQ3NDU3NSIsICJub25jZSI6ICIwMDAyV0J5YzM4YV96d0pYOWl6RTI3aHhzMWZIbGJHdExFMGtrSUlXa1ZEUUh3cyIsICJ1cmwiOiAiaHR0cHM6Ly9hY21lLXN0YWdpbmctdjAyLmFwaS5sZXRzZW5jcnlwdC5vcmcvYWNtZS9jaGFsbC12My81MzY4MTQyNy9maFE0cWcifQ",
  "signature": "AqOMX54a-356bKd-0w-ub9ov8Niv3lDpZa8B0NSpih0AtFS5Y5afdT3v3cKsPIw9HAHiV-6yCssVUNjwC6ClpATyDtdhPOrdmNkH5h-mkOfyUwLMdWfAd-U15JgKHeHOO8OpaaOoAvSA7gr-lM_gIG7EaeTUpD7FR6OhR9kjrUtIoxY3wHAHou9iSiCg9DGztgbaCqK6NYZUaaF9Ln5NHtXXThxSYKuTNIxGbMj0sqxMJq_dQl5X2kz8zniSH8jN__7va2D8cvLteCKBmfBHdm5pEbLGIk8izak1C6ok1KhdC6ohtN1xvUQKlrUgbPxcae6HvEqNSlqcvLJuhYskDQ",
  "payload": "ewogICJyZXNvdXJjZSI6ICJjaGFsbGVuZ2UiLAogICJ0eXBlIjogImRucy0wMSIKfQ"
}
2020-05-03 23:27:56,911:DEBUG:urllib3.connectionpool:https://acme-staging-v02.api.letsencrypt.org:443 "POST /acme/chall-v3/53681427/fhQ4qg HTTP/1.1" 200 190
2020-05-03 23:27:56,913:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Sun, 03 May 2020 23:27:56 GMT
Content-Type: application/json
Content-Length: 190
Connection: keep-alive
Boulder-Requester: 13474575
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-staging-v02.api.letsencrypt.org/directory>;rel="index", <https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/53681427>;rel="up"
Location: https://acme-staging-v02.api.letsencrypt.org/acme/chall-v3/53681427/fhQ4qg
Replay-Nonce: 00021xeprzwJ4Yzs6dpK18iUVLN6tZ7U2ktgAxmwZFS9m8U
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "type": "dns-01",
  "status": "pending",
  "url": "https://acme-staging-v02.api.letsencrypt.org/acme/chall-v3/53681427/fhQ4qg",
  "token": "IMpnBBejNopbCycmUcmsLdusQSz0ZW1g4eD-hgesL7c"
}
2020-05-03 23:27:56,915:DEBUG:acme.client:Storing nonce: 00021xeprzwJ4Yzs6dpK18iUVLN6tZ7U2ktgAxmwZFS9m8U
2020-05-03 23:27:57,920:DEBUG:acme.client:JWS payload:
b''
2020-05-03 23:27:57,925:DEBUG:acme.client:Sending POST request to https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/53681427:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS1zdGFnaW5nLXYwMi5hcGkubGV0c2VuY3J5cHQub3JnL2FjbWUvYWNjdC8xMzQ3NDU3NSIsICJub25jZSI6ICIwMDAyMXhlcHJ6d0o0WXpzNmRwSzE4aVVWTE42dFo3VTJrdGdBeG13WkZTOW04VSIsICJ1cmwiOiAiaHR0cHM6Ly9hY21lLXN0YWdpbmctdjAyLmFwaS5sZXRzZW5jcnlwdC5vcmcvYWNtZS9hdXRoei12My81MzY4MTQyNyJ9",
  "signature": "gvAHBXHhX_2ZAauG9dzqwzcLPd0h-z-eZ_M3MUXLvMGxz_21XArgR5x89Y8rDFkgL9PdXUm5gr3QYBpEIGp2MIZWKLWvBuZuIuJDHh6holDpf5jy9Kca1LwimI-ow5DPzXXDLddpb1KIoaeB8K_L2YA_vNDqVFcHR4Bh7o8AuOGIsCUvU5q1WRFa4NvuqOszc-UoOEfeMA1Ifcx2dbQ1v80I9BZ5sF1H8MiMXBQ4yCAh0uhuC2oT4sbCoYvbUUP-fzkZen9tCeFx8LWyNHru1o9nA4YxPCLoN2sXbYQEehnnsdkX4AN_ycmvA1OxMJrCzlh81UK6GJlojFIPH6i3EQ",
  "payload": ""
}
2020-05-03 23:27:58,117:DEBUG:urllib3.connectionpool:https://acme-staging-v02.api.letsencrypt.org:443 "POST /acme/authz-v3/53681427 HTTP/1.1" 200 630
2020-05-03 23:27:58,119:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Sun, 03 May 2020 23:27:58 GMT
Content-Type: application/json
Content-Length: 630
Connection: keep-alive
Boulder-Requester: 13474575
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-staging-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: 0002sBFU04BHqze-JH1uJMLgrPSUYsKPMDuxUVacYPC8CVo
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "identifier": {
    "type": "dns",
    "value": "a.build.kyma-project.io"
  },
  "status": "invalid",
  "expires": "2020-05-10T23:27:56Z",
  "challenges": [
    {
      "type": "dns-01",
      "status": "invalid",
      "error": {
        "type": "urn:ietf:params:acme:error:dns",
        "detail": "DNS problem: NXDOMAIN looking up TXT for _acme-challenge.a.build.kyma-project.io - check that a DNS record exists for this domain",
        "status": 400
      },
      "url": "https://acme-staging-v02.api.letsencrypt.org/acme/chall-v3/53681427/fhQ4qg",
      "token": "IMpnBBejNopbCycmUcmsLdusQSz0ZW1g4eD-hgesL7c"
    }
  ]
}
2020-05-03 23:27:58,121:DEBUG:acme.client:Storing nonce: 0002sBFU04BHqze-JH1uJMLgrPSUYsKPMDuxUVacYPC8CVo
2020-05-03 23:27:58,123:WARNING:certbot._internal.auth_handler:Challenge failed for domain a.build.kyma-project.io
2020-05-03 23:27:58,124:INFO:certbot._internal.auth_handler:dns-01 challenge for a.build.kyma-project.io
2020-05-03 23:27:58,126:DEBUG:certbot._internal.reporter:Reporting to user: The following errors were reported by the server:

Domain: a.build.kyma-project.io
Type:   dns
Detail: DNS problem: NXDOMAIN looking up TXT for _acme-challenge.a.build.kyma-project.io - check that a DNS record exists for this domain
2020-05-03 23:27:58,128:DEBUG:certbot._internal.error_handler:Encountered exception:
Traceback (most recent call last):
  File "/opt/certbot/src/certbot/certbot/_internal/auth_handler.py", line 91, in handle_authorizations
    self._poll_authorizations(authzrs, max_retries, best_effort)
  File "/opt/certbot/src/certbot/certbot/_internal/auth_handler.py", line 180, in _poll_authorizations
    raise errors.AuthorizationError('Some challenges have failed.')
certbot.errors.AuthorizationError: Some challenges have failed.

2020-05-03 23:27:58,130:DEBUG:certbot._internal.error_handler:Calling registered functions
2020-05-03 23:27:58,131:INFO:certbot._internal.auth_handler:Cleaning up challenges
2020-05-03 23:27:58,133:INFO:certbot._internal.hooks:Running manual-cleanup-hook command: /bot/certbotauthenticator
2020-05-03 23:27:58,141:ERROR:certbot._internal.hooks:manual-cleanup-hook command "/bot/certbotauthenticator" returned error code 127
2020-05-03 23:27:58,143:ERROR:certbot._internal.hooks:Error output from manual-cleanup-hook command certbotauthenticator:
/bin/sh: /bot/certbotauthenticator: not found

2020-05-03 23:27:58,144:DEBUG:certbot._internal.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/local/bin/certbot", line 11, in <module>
    load_entry_point('certbot', 'console_scripts', 'certbot')()
  File "/opt/certbot/src/certbot/certbot/main.py", line 15, in main
    return internal_main.main(cli_args)
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 1347, in main
    return config.func(config, plugins)
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 1233, in certonly
    lineage = _get_and_save_cert(le_client, config, domains, certname, lineage)
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 121, in _get_and_save_cert
    lineage = le_client.obtain_and_enroll_certificate(domains, certname)
  File "/opt/certbot/src/certbot/certbot/_internal/client.py", line 410, in obtain_and_enroll_certificate
    cert, chain, key, _ = self.obtain_certificate(domains)
  File "/opt/certbot/src/certbot/certbot/_internal/client.py", line 344, in obtain_certificate
    orderr = self._get_order_and_authorizations(csr.data, self.config.allow_subset_of_names)
  File "/opt/certbot/src/certbot/certbot/_internal/client.py", line 391, in _get_order_and_authorizations
    authzr = self.auth_handler.handle_authorizations(orderr, best_effort)
  File "/opt/certbot/src/certbot/certbot/_internal/auth_handler.py", line 91, in handle_authorizations
    self._poll_authorizations(authzrs, max_retries, best_effort)
  File "/opt/certbot/src/certbot/certbot/_internal/auth_handler.py", line 180, in _poll_authorizations
    raise errors.AuthorizationError('Some challenges have failed.')
certbot.errors.AuthorizationError: Some challenges have failed.
