2020-05-04 12:32:35,817:DEBUG:certbot._internal.main:certbot version: 1.3.0
2020-05-04 12:32:35,818:DEBUG:certbot._internal.main:Arguments: ['--agree-tos', '--no-eff-email', '-m', 'przemek.pokrywka@gmail.com', '--server', 'https://acme-staging-v02.api.letsencrypt.org/directory', '--manual', '--manual-public-ip-logging-ok', '--preferred-challenges', 'dns', '--manual-auth-hook', '/bot/certbotauthenticator', '--manual-cleanup-hook', '/bot/certbotauthenticator -D', '-d', 'a.build.kyma-project.io.']
2020-05-04 12:32:35,818:DEBUG:certbot._internal.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#manual,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2020-05-04 12:32:36,112:DEBUG:certbot._internal.log:Root logging level set at 20
2020-05-04 12:32:36,113:INFO:certbot._internal.log:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2020-05-04 12:32:36,118:DEBUG:certbot._internal.plugins.selection:Requested authenticator manual and installer None
2020-05-04 12:32:36,125:DEBUG:certbot._internal.plugins.selection:Single candidate plugin: * manual
Description: Manual configuration or run your own shell scripts
Interfaces: IAuthenticator, IPlugin
Entry point: manual = certbot._internal.plugins.manual:Authenticator
Initialized: <certbot._internal.plugins.manual.Authenticator object at 0x7f5ec1799580>
Prep: True
2020-05-04 12:32:36,126:DEBUG:certbot._internal.plugins.selection:Selected authenticator <certbot._internal.plugins.manual.Authenticator object at 0x7f5ec1799580> and installer None
2020-05-04 12:32:36,127:INFO:certbot._internal.plugins.selection:Plugins selected: Authenticator manual, Installer None
2020-05-04 12:32:36,148:DEBUG:certbot._internal.main:Picked account: <Account(RegistrationResource(body=Registration(key=None, contact=(), agreement=None, status=None, terms_of_service_agreed=None, only_return_existing=None, external_account_binding=None), uri='https://acme-staging-v02.api.letsencrypt.org/acme/acct/13474575', new_authzr_uri=None, terms_of_service=None), 0ca10773bedaf0252bc041e7c5277c08, Meta(creation_dt=datetime.datetime(2020, 5, 3, 22, 46, 17, tzinfo=<UTC>), creation_host='1fe450f9cd72'))>
2020-05-04 12:32:36,151:DEBUG:acme.client:Sending GET request to https://acme-staging-v02.api.letsencrypt.org/directory.
2020-05-04 12:32:36,154:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): acme-staging-v02.api.letsencrypt.org:443
2020-05-04 12:32:36,905:DEBUG:urllib3.connectionpool:https://acme-staging-v02.api.letsencrypt.org:443 "GET /directory HTTP/1.1" 200 724
2020-05-04 12:32:36,907:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Mon, 04 May 2020 12:32:36 GMT
Content-Type: application/json
Content-Length: 724
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "keyChange": "https://acme-staging-v02.api.letsencrypt.org/acme/key-change",
  "meta": {
    "caaIdentities": [
      "letsencrypt.org"
    ],
    "termsOfService": "https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf",
    "website": "https://letsencrypt.org/docs/staging-environment/"
  },
  "newAccount": "https://acme-staging-v02.api.letsencrypt.org/acme/new-acct",
  "newNonce": "https://acme-staging-v02.api.letsencrypt.org/acme/new-nonce",
  "newOrder": "https://acme-staging-v02.api.letsencrypt.org/acme/new-order",
  "pUha7MINgF8": "https://community.letsencrypt.org/t/adding-random-entries-to-the-directory/33417",
  "revokeCert": "https://acme-staging-v02.api.letsencrypt.org/acme/revoke-cert"
}
2020-05-04 12:32:36,966:DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): ocsp.stg-int-x1.letsencrypt.org:80
2020-05-04 12:32:36,985:DEBUG:urllib3.connectionpool:http://ocsp.stg-int-x1.letsencrypt.org:80 "POST / HTTP/1.1" 200 488
2020-05-04 12:32:36,987:DEBUG:certbot.ocsp:OCSP response for certificate /etc/letsencrypt/archive/a.build.kyma-project.io/cert1.pem is signed by the certificate's issuer.
2020-05-04 12:32:36,993:DEBUG:certbot.ocsp:OCSP certificate status for /etc/letsencrypt/archive/a.build.kyma-project.io/cert1.pem is: OCSPCertStatus.GOOD
2020-05-04 12:32:37,009:INFO:certbot._internal.renewal:Cert not yet due for renewal
2020-05-04 12:32:37,011:DEBUG:certbot._internal.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/local/bin/certbot", line 11, in <module>
    load_entry_point('certbot', 'console_scripts', 'certbot')()
  File "/opt/certbot/src/certbot/certbot/main.py", line 15, in main
    return internal_main.main(cli_args)
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 1347, in main
    return config.func(config, plugins)
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 1226, in certonly
    should_get_cert, lineage = _find_cert(config, domains, certname)
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 286, in _find_cert
    action, lineage = _find_lineage_for_domains_and_certname(config, domains, certname)
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 313, in _find_lineage_for_domains_and_certname
    return _find_lineage_for_domains(config, domains)
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 263, in _find_lineage_for_domains
    return _handle_identical_cert_request(config, ident_names_cert)
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 215, in _handle_identical_cert_request
    response = display.menu(question, choices,
  File "/opt/certbot/src/certbot/certbot/display/util.py", line 153, in menu
    code, selection = self._get_valid_int_ans(len(choices))
  File "/opt/certbot/src/certbot/certbot/display/util.py", line 411, in _get_valid_int_ans
    ans = input_with_timeout(input_msg)
  File "/opt/certbot/src/certbot/certbot/display/util.py", line 85, in input_with_timeout
    raise EOFError
EOFError
2020-05-04 12:32:37,012:ERROR:certbot._internal.log:An unexpected error occurred:
