2020-05-04 11:23:43,032:DEBUG:certbot._internal.main:certbot version: 1.3.0
2020-05-04 11:23:43,032:DEBUG:certbot._internal.main:Arguments: ['--agree-tos', '--no-eff-email', '-m', 'przemek.pokrywka@gmail.com', '--server', 'https://acme-staging-v02.api.letsencrypt.org/directory', '--manual', '--manual-public-ip-logging-ok', '--preferred-challenges', 'dns', '--manual-auth-hook', '/bot/certbotauthenticator', '--manual-cleanup-hook', '/bot/certbotauthenticator', '-d', 'a.build.kyma-project.io.']
2020-05-04 11:23:43,032:DEBUG:certbot._internal.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#manual,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2020-05-04 11:23:43,364:DEBUG:certbot._internal.log:Root logging level set at 20
2020-05-04 11:23:43,365:INFO:certbot._internal.log:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2020-05-04 11:23:43,372:DEBUG:certbot._internal.plugins.selection:Requested authenticator manual and installer None
2020-05-04 11:23:43,382:DEBUG:certbot._internal.plugins.selection:Single candidate plugin: * manual
Description: Manual configuration or run your own shell scripts
Interfaces: IAuthenticator, IPlugin
Entry point: manual = certbot._internal.plugins.manual:Authenticator
Initialized: <certbot._internal.plugins.manual.Authenticator object at 0x7fef458230a0>
Prep: True
2020-05-04 11:23:43,383:DEBUG:certbot._internal.plugins.selection:Selected authenticator <certbot._internal.plugins.manual.Authenticator object at 0x7fef458230a0> and installer None
2020-05-04 11:23:43,384:INFO:certbot._internal.plugins.selection:Plugins selected: Authenticator manual, Installer None
2020-05-04 11:23:43,406:DEBUG:certbot._internal.main:Picked account: <Account(RegistrationResource(body=Registration(key=None, contact=(), agreement=None, status=None, terms_of_service_agreed=None, only_return_existing=None, external_account_binding=None), uri='https://acme-staging-v02.api.letsencrypt.org/acme/acct/13474575', new_authzr_uri=None, terms_of_service=None), 0ca10773bedaf0252bc041e7c5277c08, Meta(creation_dt=datetime.datetime(2020, 5, 3, 22, 46, 17, tzinfo=<UTC>), creation_host='1fe450f9cd72'))>
2020-05-04 11:23:43,407:DEBUG:acme.client:Sending GET request to https://acme-staging-v02.api.letsencrypt.org/directory.
2020-05-04 11:23:43,410:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): acme-staging-v02.api.letsencrypt.org:443
2020-05-04 11:23:44,187:DEBUG:urllib3.connectionpool:https://acme-staging-v02.api.letsencrypt.org:443 "GET /directory HTTP/1.1" 200 724
2020-05-04 11:23:44,189:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Mon, 04 May 2020 11:23:44 GMT
Content-Type: application/json
Content-Length: 724
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "keyChange": "https://acme-staging-v02.api.letsencrypt.org/acme/key-change",
  "meta": {
    "caaIdentities": [
      "letsencrypt.org"
    ],
    "termsOfService": "https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf",
    "website": "https://letsencrypt.org/docs/staging-environment/"
  },
  "mkPHT-l5i3o": "https://community.letsencrypt.org/t/adding-random-entries-to-the-directory/33417",
  "newAccount": "https://acme-staging-v02.api.letsencrypt.org/acme/new-acct",
  "newNonce": "https://acme-staging-v02.api.letsencrypt.org/acme/new-nonce",
  "newOrder": "https://acme-staging-v02.api.letsencrypt.org/acme/new-order",
  "revokeCert": "https://acme-staging-v02.api.letsencrypt.org/acme/revoke-cert"
}
2020-05-04 11:23:44,194:INFO:certbot._internal.main:Obtaining a new certificate
2020-05-04 11:23:44,262:DEBUG:certbot.crypto_util:Generating key (2048 bits): /etc/letsencrypt/keys/0020_key-certbot.pem
2020-05-04 11:23:44,274:DEBUG:certbot.crypto_util:Creating CSR: /etc/letsencrypt/csr/0020_csr-certbot.pem
2020-05-04 11:23:44,275:DEBUG:acme.client:Requesting fresh nonce
2020-05-04 11:23:44,276:DEBUG:acme.client:Sending HEAD request to https://acme-staging-v02.api.letsencrypt.org/acme/new-nonce.
2020-05-04 11:23:44,462:DEBUG:urllib3.connectionpool:https://acme-staging-v02.api.letsencrypt.org:443 "HEAD /acme/new-nonce HTTP/1.1" 200 0
2020-05-04 11:23:44,465:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Mon, 04 May 2020 11:23:44 GMT
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-staging-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: 0001-SFmyQ1AbhpW2zs9JceESMP9mXfgyJ_XvE4uSJ0t12I
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800


2020-05-04 11:23:44,466:DEBUG:acme.client:Storing nonce: 0001-SFmyQ1AbhpW2zs9JceESMP9mXfgyJ_XvE4uSJ0t12I
2020-05-04 11:23:44,467:DEBUG:acme.client:JWS payload:
b'{\n  "identifiers": [\n    {\n      "type": "dns",\n      "value": "a.build.kyma-project.io"\n    }\n  ]\n}'
2020-05-04 11:23:44,471:DEBUG:acme.client:Sending POST request to https://acme-staging-v02.api.letsencrypt.org/acme/new-order:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS1zdGFnaW5nLXYwMi5hcGkubGV0c2VuY3J5cHQub3JnL2FjbWUvYWNjdC8xMzQ3NDU3NSIsICJub25jZSI6ICIwMDAxLVNGbXlRMUFiaHBXMnpzOUpjZUVTTVA5bVhmZ3lKX1h2RTR1U0owdDEySSIsICJ1cmwiOiAiaHR0cHM6Ly9hY21lLXN0YWdpbmctdjAyLmFwaS5sZXRzZW5jcnlwdC5vcmcvYWNtZS9uZXctb3JkZXIifQ",
  "signature": "2keuGKwTf6sUm6vZeYKIp_UQH1LpMDXyDuE-dJpW5hUfOVczi254RXxVfom7S5aYSHZmhARKQmpK7YgOy48vBAfVfERKLd4DFmbYSUvqzB5rAp7p0RISaZCJc_DfbhJ8ltnDd9VyrNFb1lQ6PHC6yaF_6bW5Tur65uEOP5Aw_BeL4Pz5ivVDCai-CyIH2i8UWR9k3b4qdEBNrvRTukWPPILoJjV3utL7C5OFSIyJA_0QOhQdY_ODuNa4jDJuksWsTRZux5J2w7pjgncyvNqrZu5S3FCaqjFEjFNHuTqEclMTYJhYxwT9t7Oy2k5uMeqLOktOoIlaZ6GSPHayXA1Zrg",
  "payload": "ewogICJpZGVudGlmaWVycyI6IFsKICAgIHsKICAgICAgInR5cGUiOiAiZG5zIiwKICAgICAgInZhbHVlIjogImEuYnVpbGQua3ltYS1wcm9qZWN0LmlvIgogICAgfQogIF0KfQ"
}
2020-05-04 11:23:44,681:DEBUG:urllib3.connectionpool:https://acme-staging-v02.api.letsencrypt.org:443 "POST /acme/new-order HTTP/1.1" 201 365
2020-05-04 11:23:44,683:DEBUG:acme.client:Received response:
HTTP 201
Server: nginx
Date: Mon, 04 May 2020 11:23:44 GMT
Content-Type: application/json
Content-Length: 365
Connection: keep-alive
Boulder-Requester: 13474575
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-staging-v02.api.letsencrypt.org/directory>;rel="index"
Location: https://acme-staging-v02.api.letsencrypt.org/acme/order/13474575/89520922
Replay-Nonce: 0002XSF4J3ljO6lbgbFWKq82yQDJ4AvNEI68hx6jzubVucE
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "status": "pending",
  "expires": "2020-05-11T11:23:44.578716487Z",
  "identifiers": [
    {
      "type": "dns",
      "value": "a.build.kyma-project.io"
    }
  ],
  "authorizations": [
    "https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/53827541"
  ],
  "finalize": "https://acme-staging-v02.api.letsencrypt.org/acme/finalize/13474575/89520922"
}
2020-05-04 11:23:44,685:DEBUG:acme.client:Storing nonce: 0002XSF4J3ljO6lbgbFWKq82yQDJ4AvNEI68hx6jzubVucE
2020-05-04 11:23:44,686:DEBUG:acme.client:JWS payload:
b''
2020-05-04 11:23:44,688:DEBUG:acme.client:Sending POST request to https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/53827541:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS1zdGFnaW5nLXYwMi5hcGkubGV0c2VuY3J5cHQub3JnL2FjbWUvYWNjdC8xMzQ3NDU3NSIsICJub25jZSI6ICIwMDAyWFNGNEozbGpPNmxiZ2JGV0txODJ5UURKNEF2TkVJNjhoeDZqenViVnVjRSIsICJ1cmwiOiAiaHR0cHM6Ly9hY21lLXN0YWdpbmctdjAyLmFwaS5sZXRzZW5jcnlwdC5vcmcvYWNtZS9hdXRoei12My81MzgyNzU0MSJ9",
  "signature": "3juDnIplpsFg_pPSHnBTnJtg59Kcszdxom9mz2h2wuETVPwLFGZGEsIvbEetWH0DGqISRRGiSh9u4wTyvDiA5GJoB2bKxLXVaA-08xeyWbJKux_G1aTstP_y9MXwtaMlceKh8DAp6ZfGviCJ3LK2x9pL6Lk7JG6nocvYsBFDkSwUIKDHCHOwEJYVdNBhvtE06jFg7wbl8bcfx_vMukrFSMHRPhGdFzZIKUPhQgpSujX-b2IitfP-6RBiTikud1N5HcQ_Oa_8RK4phHhjjYi9IegXg2GqBGwHCgRUxmX1NOfD3dS23hW3wDcQB3tjkA3uOPsBbuYa5T3oWbJhmQ5DVw",
  "payload": ""
}
2020-05-04 11:23:44,878:DEBUG:urllib3.connectionpool:https://acme-staging-v02.api.letsencrypt.org:443 "POST /acme/authz-v3/53827541 HTTP/1.1" 200 819
2020-05-04 11:23:44,881:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Mon, 04 May 2020 11:23:44 GMT
Content-Type: application/json
Content-Length: 819
Connection: keep-alive
Boulder-Requester: 13474575
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-staging-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: 0001XR5o3Xg2Un_uYAfP2u2_iVWC9pepMCJeZz8-ba0ePAU
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "identifier": {
    "type": "dns",
    "value": "a.build.kyma-project.io"
  },
  "status": "pending",
  "expires": "2020-05-11T11:23:44Z",
  "challenges": [
    {
      "type": "http-01",
      "status": "pending",
      "url": "https://acme-staging-v02.api.letsencrypt.org/acme/chall-v3/53827541/NmgmzQ",
      "token": "VwP-csTebpxbl1TFc-Q3sGjZTcF879c9YqLRV0wkuv0"
    },
    {
      "type": "dns-01",
      "status": "pending",
      "url": "https://acme-staging-v02.api.letsencrypt.org/acme/chall-v3/53827541/0JUDTg",
      "token": "VwP-csTebpxbl1TFc-Q3sGjZTcF879c9YqLRV0wkuv0"
    },
    {
      "type": "tls-alpn-01",
      "status": "pending",
      "url": "https://acme-staging-v02.api.letsencrypt.org/acme/chall-v3/53827541/QLLkXg",
      "token": "VwP-csTebpxbl1TFc-Q3sGjZTcF879c9YqLRV0wkuv0"
    }
  ]
}
2020-05-04 11:23:44,882:DEBUG:acme.client:Storing nonce: 0001XR5o3Xg2Un_uYAfP2u2_iVWC9pepMCJeZz8-ba0ePAU
2020-05-04 11:23:44,884:INFO:certbot._internal.auth_handler:Performing the following challenges:
2020-05-04 11:23:44,885:INFO:certbot._internal.auth_handler:dns-01 challenge for a.build.kyma-project.io
2020-05-04 11:23:44,890:INFO:certbot._internal.hooks:Running manual-auth-hook command: /bot/certbotauthenticator
2020-05-04 11:23:46,405:INFO:certbot._internal.hooks:Output from manual-auth-hook command certbotauthenticator:
recordaddedtime="2020-05-04T11:23:46Z" level=fatal msg="error when changing record: googleapi: Error 400: Invalid value for 'entity.change.additions[0].name': '_acme-challenge.a.build.kyma-project.io', invalid"

2020-05-04 11:23:46,407:ERROR:certbot._internal.hooks:manual-auth-hook command "/bot/certbotauthenticator" returned error code 1
2020-05-04 11:23:46,412:INFO:certbot._internal.auth_handler:Waiting for verification...
2020-05-04 11:23:46,414:DEBUG:acme.client:JWS payload:
b'{\n  "resource": "challenge",\n  "type": "dns-01"\n}'
2020-05-04 11:23:46,417:DEBUG:acme.client:Sending POST request to https://acme-staging-v02.api.letsencrypt.org/acme/chall-v3/53827541/0JUDTg:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS1zdGFnaW5nLXYwMi5hcGkubGV0c2VuY3J5cHQub3JnL2FjbWUvYWNjdC8xMzQ3NDU3NSIsICJub25jZSI6ICIwMDAxWFI1bzNYZzJVbl91WUFmUDJ1Ml9pVldDOXBlcE1DSmVaejgtYmEwZVBBVSIsICJ1cmwiOiAiaHR0cHM6Ly9hY21lLXN0YWdpbmctdjAyLmFwaS5sZXRzZW5jcnlwdC5vcmcvYWNtZS9jaGFsbC12My81MzgyNzU0MS8wSlVEVGcifQ",
  "signature": "YjNPEJkfXNptbqv3QAkter2BW4jP5U1fpxd4sqaW-xHQEYLRWh6qt0rHzgNd4Vup_gxIlVd5Sq_Yj4iLxZwSIAR4XV8hmLsJtbVyCColulURhHX4DShgX8LPGa3KtJwzfsKISEVNL7wLkQwALVMqtCvfS4Iv1Bsu6LCLjaUXGGlHMDPaWtDYF8RUfXJuBpAQQWC36vXESQr6q0O8rGfAUvrqHbu7ocdfjxIy_L6pdB1dH4EIEsIrefr2d7C5YLD61whnBbF3uTO-iQAG98wxNX0-Y5t8OaFqWS3_jQh29lIerqVAzoM-sSxEv-Wfpi9JpMvILDwxGIGqQupGUlmiVQ",
  "payload": "ewogICJyZXNvdXJjZSI6ICJjaGFsbGVuZ2UiLAogICJ0eXBlIjogImRucy0wMSIKfQ"
}
2020-05-04 11:23:46,610:DEBUG:urllib3.connectionpool:https://acme-staging-v02.api.letsencrypt.org:443 "POST /acme/chall-v3/53827541/0JUDTg HTTP/1.1" 200 190
2020-05-04 11:23:46,612:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Mon, 04 May 2020 11:23:46 GMT
Content-Type: application/json
Content-Length: 190
Connection: keep-alive
Boulder-Requester: 13474575
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-staging-v02.api.letsencrypt.org/directory>;rel="index", <https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/53827541>;rel="up"
Location: https://acme-staging-v02.api.letsencrypt.org/acme/chall-v3/53827541/0JUDTg
Replay-Nonce: 000278V2VqWbtJp6HziVwBxhCvs-g1T0FEwUWJ5w-g2ATmQ
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "type": "dns-01",
  "status": "pending",
  "url": "https://acme-staging-v02.api.letsencrypt.org/acme/chall-v3/53827541/0JUDTg",
  "token": "VwP-csTebpxbl1TFc-Q3sGjZTcF879c9YqLRV0wkuv0"
}
2020-05-04 11:23:46,614:DEBUG:acme.client:Storing nonce: 000278V2VqWbtJp6HziVwBxhCvs-g1T0FEwUWJ5w-g2ATmQ
2020-05-04 11:23:47,618:DEBUG:acme.client:JWS payload:
b''
2020-05-04 11:23:47,622:DEBUG:acme.client:Sending POST request to https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/53827541:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS1zdGFnaW5nLXYwMi5hcGkubGV0c2VuY3J5cHQub3JnL2FjbWUvYWNjdC8xMzQ3NDU3NSIsICJub25jZSI6ICIwMDAyNzhWMlZxV2J0SnA2SHppVndCeGhDdnMtZzFUMEZFd1VXSjV3LWcyQVRtUSIsICJ1cmwiOiAiaHR0cHM6Ly9hY21lLXN0YWdpbmctdjAyLmFwaS5sZXRzZW5jcnlwdC5vcmcvYWNtZS9hdXRoei12My81MzgyNzU0MSJ9",
  "signature": "RC2sBEr-8g-pUjsow9F2DqStJHKtXCb0vTqlSySQ6rLXVlaWxyEhVB-AL3IaiJtnodsJ7zSiftjdrLIFtSrD9RFOcDS7mw7p2us0PCKBMhIAsWzLRC3MxSlkzo6Kcyo036wMhtGvuypO5H9UfzUuwlejXgkCxk-Nrr7sx-nKzzqUjrTEnjJruACDXBw_ahwU-jx4KoYj2fJJ0-7QEnOA8F9tzboYRIlvw31clCamM520oz_Lx1dLsm_Bmv5obWXiUj6LsMsXNvZ9rZXI_Wjk0xL0_5slruaOm6D_0rzvMDzAPtN5hK6JG-zDI4oeXVVDo-FSvTiDe74h_AgG3YRi0w",
  "payload": ""
}
2020-05-04 11:23:47,815:DEBUG:urllib3.connectionpool:https://acme-staging-v02.api.letsencrypt.org:443 "POST /acme/authz-v3/53827541 HTTP/1.1" 200 630
2020-05-04 11:23:47,818:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Mon, 04 May 2020 11:23:47 GMT
Content-Type: application/json
Content-Length: 630
Connection: keep-alive
Boulder-Requester: 13474575
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-staging-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: 00019GVb3AVOEcKtek1KIpCwflZ9Zp0HTZMiEZf_odQKmVA
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "identifier": {
    "type": "dns",
    "value": "a.build.kyma-project.io"
  },
  "status": "invalid",
  "expires": "2020-05-11T11:23:44Z",
  "challenges": [
    {
      "type": "dns-01",
      "status": "invalid",
      "error": {
        "type": "urn:ietf:params:acme:error:dns",
        "detail": "DNS problem: NXDOMAIN looking up TXT for _acme-challenge.a.build.kyma-project.io - check that a DNS record exists for this domain",
        "status": 400
      },
      "url": "https://acme-staging-v02.api.letsencrypt.org/acme/chall-v3/53827541/0JUDTg",
      "token": "VwP-csTebpxbl1TFc-Q3sGjZTcF879c9YqLRV0wkuv0"
    }
  ]
}
2020-05-04 11:23:47,819:DEBUG:acme.client:Storing nonce: 00019GVb3AVOEcKtek1KIpCwflZ9Zp0HTZMiEZf_odQKmVA
2020-05-04 11:23:47,821:WARNING:certbot._internal.auth_handler:Challenge failed for domain a.build.kyma-project.io
2020-05-04 11:23:47,822:INFO:certbot._internal.auth_handler:dns-01 challenge for a.build.kyma-project.io
2020-05-04 11:23:47,825:DEBUG:certbot._internal.reporter:Reporting to user: The following errors were reported by the server:

Domain: a.build.kyma-project.io
Type:   dns
Detail: DNS problem: NXDOMAIN looking up TXT for _acme-challenge.a.build.kyma-project.io - check that a DNS record exists for this domain
2020-05-04 11:23:47,827:DEBUG:certbot._internal.error_handler:Encountered exception:
Traceback (most recent call last):
  File "/opt/certbot/src/certbot/certbot/_internal/auth_handler.py", line 91, in handle_authorizations
    self._poll_authorizations(authzrs, max_retries, best_effort)
  File "/opt/certbot/src/certbot/certbot/_internal/auth_handler.py", line 180, in _poll_authorizations
    raise errors.AuthorizationError('Some challenges have failed.')
certbot.errors.AuthorizationError: Some challenges have failed.

2020-05-04 11:23:47,828:DEBUG:certbot._internal.error_handler:Calling registered functions
2020-05-04 11:23:47,829:INFO:certbot._internal.auth_handler:Cleaning up challenges
2020-05-04 11:23:47,831:INFO:certbot._internal.hooks:Running manual-cleanup-hook command: /bot/certbotauthenticator
2020-05-04 11:23:47,916:ERROR:certbot._internal.hooks:manual-cleanup-hook command "/bot/certbotauthenticator" returned error code 2
2020-05-04 11:23:47,918:ERROR:certbot._internal.hooks:Error output from manual-cleanup-hook command certbotauthenticator:
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x8b7779]

goroutine 1 [running]:
github.com/kyma-project/test-infra/development/gcp/pkg/dnsclient.(*DNSClient).DoChange(0xc00035fbe8, 0xac52a0, 0xc000116000, 0x0, 0x0, 0xc00005eb40, 0x0)
	/go/src/github.com/kyma-project/test-infra/development/gcp/pkg/dnsclient/client.go:98 +0x39
main.main()
	/go/src/github.com/kyma-project/test-infra/development/gcp/cmd/certbotauthenticator/main.go:47 +0x485

2020-05-04 11:23:47,919:DEBUG:certbot._internal.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/local/bin/certbot", line 11, in <module>
    load_entry_point('certbot', 'console_scripts', 'certbot')()
  File "/opt/certbot/src/certbot/certbot/main.py", line 15, in main
    return internal_main.main(cli_args)
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 1347, in main
    return config.func(config, plugins)
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 1233, in certonly
    lineage = _get_and_save_cert(le_client, config, domains, certname, lineage)
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 121, in _get_and_save_cert
    lineage = le_client.obtain_and_enroll_certificate(domains, certname)
  File "/opt/certbot/src/certbot/certbot/_internal/client.py", line 410, in obtain_and_enroll_certificate
    cert, chain, key, _ = self.obtain_certificate(domains)
  File "/opt/certbot/src/certbot/certbot/_internal/client.py", line 344, in obtain_certificate
    orderr = self._get_order_and_authorizations(csr.data, self.config.allow_subset_of_names)
  File "/opt/certbot/src/certbot/certbot/_internal/client.py", line 391, in _get_order_and_authorizations
    authzr = self.auth_handler.handle_authorizations(orderr, best_effort)
  File "/opt/certbot/src/certbot/certbot/_internal/auth_handler.py", line 91, in handle_authorizations
    self._poll_authorizations(authzrs, max_retries, best_effort)
  File "/opt/certbot/src/certbot/certbot/_internal/auth_handler.py", line 180, in _poll_authorizations
    raise errors.AuthorizationError('Some challenges have failed.')
certbot.errors.AuthorizationError: Some challenges have failed.
